version: '3'

services:
  stock_app:
    build:
      context: ./stock_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - fundamental_analysis_service
      - technical_analysis_service
      - lstm_prediction_service
      - scraping_service
    volumes:
      - ./data:/app/data

  fundamental_analysis_service:
    build:
      context: ./microservices/fundamental_analysis_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./data:/app/data

  technical_analysis_service:
    build:
      context: ./microservices/technical_analysis_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data

  lstm_prediction_service:
    build:
      context: ./microservices/lstm_prediction_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data

  scraping_service:
    build:
      context: ./microservices/scraping_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./data:/app/data